baseURL = "/"
languageCode = "en-GB"
contentDir = "content"
enableEmoji = true
title = 'My New Hugo Site'
theme = "lotusdocs"

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params.docs]
  # The default docs section
  pathName = "docs"

[[menu.main]]
  name = "Product A"
  url = "/product-a/"
  weight = 1

[[menu.main]]
  name = "Product B"
  url = "/product-b/"
  weight = 2